export const REGISTER_START = 'REGISTER_START'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_ERROR = 'REGISTER_ERROR'

export const LOGIN_START = 'REGISTER_START'
export const LOGIN_SUCCESS = 'REGISTER_SUCCESS'
export const LOGIN_ERROR = 'REGISTER_ERROR'

export const LOGOUT_START = 'REGISTER_START'
export const LOGOUT_SUCCESS = 'REGISTER_SUCCESS'
export const LOGOUT_ERROR = 'REGISTER_ERROR'